version: '3.8'

volumes:
  readsbpb_rrd:
  readsbpb_autogain:
  tar1090_heatmap:

services:
   #readsb:
   # image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest_i386
   # tty: true
   # container_name: readsb
   # hostname: readsb
   # restart: always
   # devices:
   #   - /dev/bus/usb:/dev/bus/usb
   # ports:
   #   - 8080:8080
   # environment:
   #   - TZ=${FEEDER_TZ}
   #   - READSB_DEVICE_TYPE=rtlsdr
   #   - READSB_RTLSDR_DEVICE=1090
   #   - READSB_GAIN=autogain
   #   - READSB_LAT=${FEEDER_LAT}
   #   - READSB_LON=${FEEDER_LONG}
   #   - READSB_RX_LOCATION_ACCURACY=2
   #  - READSB_STATS_RANGE=true
   #   - READSB_NET_ENABLE=true
   # volumes:
   #   - readsbpb_rrd:/run/collectd
   #   - readsbpb_autogain:/run/autogain
   # tmpfs:
   #   - /run/readsb
   #   - /var/log
   piaware:
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest
    tty: true
    container_name: piaware
    restart: always
    #depends_on:
    #  - readsb
    ports:
      - 8081:8080
    environment:
      - BEASTHOST=192.168.170.7
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TZ=${FEEDER_TZ}
      - FEEDER_ID=${PIAWARE_FEEDER_ID}
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    env_file:
      - stack.env
   flightradar24:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
    tty: true
    container_name: flightradar24
    restart: always
    #depends_on:
    #  - readsb
    ports:
      - 8754:8754
    environment:
      - BEASTHOST=192.168.170.7
      - TZ=${FEEDER_TZ}
      - FR24KEY=${FR24_SHARING_KEY}
      - MLAT=yes
    tmpfs:
      - /var/log
    env_file:
      - stack.env
   tar1090:
    image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    environment:
      - UPDATE_TAR1090=false
      - TZ=${FEEDER_TZ}
      - BEASTHOST=192.168.170.7
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
    ports:
      - 8082:80
    volumes:
      - "tar1090_heatmap:/var/globe_history"
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    env_file:
      - stack.env
   watchtower:
    image: containrrr/watchtower:latest
    tty: true
    container_name: watchtower
    restart: always
    environment:
      - TZ=${FEEDER_TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
